name: php_MonBlog
on:
  push:
    branches : ["main","develop"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: build image php_MonBlog
    run: docker build -t testimage . 