name: php_MonBlog
on:
  push:
    branches : ["main","develop"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: tester le code 
        run: echo "hellow tester you do it right"

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: build image php_MonBlog
      run: docker build -t testimage . 